### ISSUE TITLE
Abiturzeugnis Sprachenfolge

### ISSUE THREAD

**Issue by FPfotenhauer** [SVWS-NRW/Schild-NRW-Zeugnisse-Sek1#15]
https://schulverwaltungsinfos.nrw.de/svws/forum/viewtopic.php?p=11278#p11278

**Comment by mueller-falko** [comment]
Sehe nur ich das so, oder ist die Abfrage
Detail.Visible := ((Sprachenfolge['Reihenfolge'] <> 'P') or (Sprachenfolge['Reihenfolge'] = 'P'));
redundant? Die Aussage ist doch immer wahr, daher könnte man einfach 
Detail.Visible:=true; 
setzen.
In der ursprünglichen Programmierung ging es doch offenbar genau darum, die Sprachprüfungen nicht anzuzeigen. Warum auch immer.

**Comment by mueller-falko** [comment]
https://schulverwaltungsinfos.nrw.de/svws/forum/viewtopic.php?f=4&t=1452
Hier schreibt Herr Hoebig, dass Sprachfeststellungsprüfungen nicht in der Tabelle Referenzniveaus angegeben wird. Vielleicht sollte man das nochmal klären.

**Comment by FPfotenhauer** [comment]
Hinzu komme auch, dass die aktuellen Abizeugnisse nicht für G9-Gy geeignet sind.
Ich habe denen angepasste Zeugnisse gesendet.
Die neuen Zuegnisse müssen das ja dann so oder so können...

**Comment by mueller-falko** [comment]
Gehört in die Sek II
