### ISSUE TITLE
Fehlermelung bei Zeugnis 5-10

### ISSUE THREAD

**Issue by FPfotenhauer** [SVWS-NRW/Schild-NRW-Zeugnisse-Sek1#21]
https://schulverwaltungsinfos.nrw.de/svws/forum/viewtopic.php?f=16&t=2011&p=11534#p11534

Bei fast allen Zeugnissen Sek15-10  kommt eine Fehlermeldung, wenn man den Report in der 10.2 druckt.

Das ist eigentlich egal, weil die dort nicht verwendet werden sollten.
Aber es ist unschön, vielleicht kann man das irgendwie abfangen.

An der GE tritt das am häufigsten auf, weil dort Schüler der 10 in die EF gehen...

**Comment by M-Plu** [comment]
Sollte mit der Zeugnisversion vom Oktober 2021 behoben sein.
