### ISSUE TITLE
Versetzungsvermerk VV

### ISSUE THREAD

**Issue by FPfotenhauer** [SVWS-NRW/Schild-NRW-Zeugnisse-Sek1#31]
Falko hatte das per Mail geschrieben.
Nur damit es nicht vergessen wird:

beim Testen der angepassten Inklusionszeugnisse von Herrn de la Haye ist
mir ein Problem beim Versetzungsvermerk aufgefallen, das alle unsere
Zeugnisse betrifft: Der Umgang mit vorversetzten SuS ist nicht sauber
programmiert.

Beim Gymnasium (Anlage 31u35) funktioniert VV gar nicht. Habe den Fehler
noch nicht gefunden.

Bei allen anderen Schulformen gibt es folgende Problemfälle:

Fall 1: eine Schule benutzt für die Klassen 5-9 Bezeichnungen ohne
führende Null:
Die Berechnung beim Versetzungsfeld nimmt die ersten beiden Zeichen der
Folgeklasse als Folgestufe und löscht dann erst eine mögliche führende
Null. Für den Klassenbuchstaben werden die ersten beiden Zeichen der
Folgeklasse gelöscht. Das führt bei dieser Schule dazu, dass z.B. bei
Folgeklasse '7a' im Report die Folgestufe '7a' lautet und der
Klassenbuchstabe leer ist. Das fällt bei der normalen Versetzung nicht
auf, da die beiden Strings einfach wieder zusammengesetzt werden. Bei
der Vorversetzung wird aber die Folgestufe in eine Integer umgewandelt
um dann um eins erhöht zu werden. Das führt hier natürlich zu einer
Fehlermeldung.

Fall 2: Jemand trägt bei einem Schüler aus z.B. der '06A' den Vermerk
'VV' ein und ändert die Folgeklasse direkt auf '08A'.
Auf dem Zeugnis steht dann "Wird in die Klasse 9 versetzt."

Der einzige Report, der immer richtige Ergebnisse ausgibt, ist das
Zeugnis "GY_Inklusion_Zeugnis_JgSt_5_9_A3_V0706.rtm".
Dort wird mit der zusätzlichen integer Variable

aktuellestufe := Lernabschnitte['Jahrgang'];

gearbeitet. Leider kann man die Berechnung nicht komplett auf andere
Zeugnisse übertragen, da der Versetzungstext ja schulformabhängig ist.
Ich denke daher, dass wir uns an der Programmierung aus den
GY_Inklusions-Zeugnis orientieren müssen und jeweils die
Versetzungsfelder anpassen müssen.

**Comment by M-Plu** [comment]
Für den Fall 2 müssten wir uns darauf verständigen, ob wir grundsätzlich den Eintrag Folgeklasse verwenden oder nicht. Ich denke fast es ist besser, wenn wir die Folgeklasse und -stufe selbst berechnen (auf Basis der Versetzungskürzels). Was meint ihr dazu?

**Comment by M-Plu** [comment]
Ach so: Der Fehler zu VV am Gymnasium sollte im angehängten Zeugnis korrigiert sein (hatte ich per E-Mail schon versendet). Das Zeugnis verwendet auch aktuellestufe := Lernabschnitte['Jahrgang'];

[Anlage 31u35 - Zeugnis 05-10 - V08_10 - NeuerVersetzText.zip](https://github.com/SVWS-NRW/Zeugnisse-NRW/files/5125605/Anlage.31u35.-.Zeugnis.05-10.-.V08_10.-.NeuerVersetzText.zip)

**Comment by mueller-falko** [comment]
Ich bin gerade dabei, die Versetzungsberechnung neu zu programmieren, zum einen um die Fehler auszumerzen, zum anderen um sie etwas übersichtlicher für Nicht-Experten zu machen. Dabei berechne ich die Folgeklasse selber, vergleiche aber noch mit dem Eintrag aus Schild, falls bereits eine andere Parallelklasse eingetragen ist. Ich denke, ich werde in ein paar Tagen ein erstes Ergebnis zum Testen rumschicken können.

**Comment by M-Plu** [comment]
Hallo Falko, 

im Anhang ist ja schon ein Ergebnis. Da würde nur die eigene Berechnung fehlen. Der Rest müsste funktionieren.

**Comment by M-Plu** [comment]
Hier die Variante mit eigener Berechn
[Anlage 31u35 - Zeugnis 05-10 - V08_10 - NeuerVersetzTextUndBerechneteFolgeStufe.zip](https://github.com/SVWS-NRW/Zeugnisse-NRW/files/5125890/Anlage.31u35.-.Zeugnis.05-10.-.V08_10.-.NeuerVersetzTextUndBerechneteFolgeStufe.zip)
ung der Folgestufe und Einbeziehung evtl. Änderungen der Parallelität.
