### ISSUE TITLE
Neue Programmierung für Versetzungsvermerk

### ISSUE THREAD

**Issue by mueller-falko** [SVWS-NRW/Schild-NRW-Zeugnisse-Sek1#36]
Ich habe im Zeugnis GE Anlage 39u40 eine neue Programmierung des Versetzungsvermerks im Subreport_Versetzung erstellt, um zum einen Issues #21  und #31 zu bearbeiten, zum anderen aber auch, um eine einfacherer Programmierung zu haben, die möglicherweise leichter nachvollziehbar ist. 
Ich bitte alle, möglichst viele Varianten der Versetzung zu testen und hier Rückmeldung zu geben.

Wenn alles klappt, könnte man theoretisch die Programmierung für alle Schulformen übernehmen. Man muss dann nur in Zeile 24 den Wert "VersetzungAbStufe" anpassen und schauen, ob es bei den einzelnen Versetzungsarten schulformspezifische Besonderheiten gibt.

**Comment by beaumart** [comment]
Hallo Falko,
ich hab bisher nur einen kleinen Formatierungsfehler gefunden.
Im Bereich, wo der Versetzungstext zusammengesetzt wird muss hinter + g89 + noch ein Leerzeichen gesetzt werden: statt ....+ g89 + 'versetzt ..... => ....+ g89 + ' versetzt ....
Hartmut

**Comment by mueller-falko** [comment]
Danke, hab ich jetzt ergänzt.

**Comment by mueller-falko** [comment]
Die neue Programmierung ist jetzt in den Versetzungszeugnissen aller Schulformen enthalten.

**Comment by M-Plu** [comment]
Sollte mit der Zeugnisversion vom Oktober 2021 behoben sein.
