### ISSUE TITLE
RS SGL H Einrückung

### ISSUE THREAD

**Issue by FPfotenhauer** [SVWS-NRW/Schild-NRW-Zeugnisse-Sek1#41]
Nur, damit es nicht vergessen wird:
https://schulverwaltungsinfos.nrw.de/svws/forum/viewtopic.php?p=15849#p15849

**Comment by mueller-falko** [comment]
Hab das Layout der Hinweise in den Anlagen 25 bis 30 bearbeitet und im DEV abgelegt. Bitte kurz überprüfen.

**Comment by M-Plu** [comment]
Leider existiert der Forenbeitrag nicht mehr. Wisst ihr noch, ob das Problem gelöst wurde. Wenn ja, kann es hier geschlossen werden.
