### ISSUE TITLE
Namenszusätze

### ISSUE THREAD

**Issue by FPfotenhauer** [SVWS-NRW/Schild-NRW-Zeugnisse-Sek1#42]
https://schulverwaltungsinfos.nrw.de/svws/forum/viewtopic.php?p=16208#p16208

Es könnte überlegt werden, ob wir das noch unterstützen.

**Comment by mueller-falko** [comment]
Es scheint so zu sein, dass das Kombifeld VornameName den Nachnamenszusatz berücksichtigt. Ich habe das mal in Anlage 31u35 eingebaut und im DEV hochgeladen. Habe es im Label DBTe_Name einprogrammiert. Wenn das so gewünscht ist, kann man es in die anderen Anlagen übernehmen.

**Comment by mueller-falko** [comment]
Soll ich die Anlage im Forum hochladen?

**Comment by FPfotenhauer** [comment]
Ja, das wäre super, dann ist dem Kollegen sofort geholfen.

**Comment by M-Plu** [comment]
Ich werde das auch in die Sek-II Zeugnisse übernehmen. Die Frage wäre, ob wir von dort das Prinzip übernehmen, dass die Namen zum Druck in zwei Programmen zusammengesetzt werden. Dann muss man das nur an einer Stelle später pflegen.

**Comment by Raffenberg** [comment]
Hallo Zusammen,
ich bin durch Zufall auf Eure Diskussion gestoßen und möchte mal eine Lanze dafür brechen, das Ganze mit dem Namenszusatz zu lassen. Mir ist bis heute kein einziges Formular aus dem Internet oder der Behörde bekannt, wo jemals ein Namenszusatz abgefragt wurde. Noch nicht einmal beim Personalausweis. Da gibt es nur Vorname, Nachname und Doktorgrad. Für die Schule wichtig ist nur noch der Rufname des Kindes (so wie die Felder in der Grundschule angezeigt werden). Nur in Schild wird ein solches Feld angeboten, was regelmäßig unnötig zu solchen Diskussionen wie im Forum führt. Dabei ist die Behandlung der Namenszusätze nicht so trivial, wie es im Duden beschrieben ist, weil diese unscharf definiert sind. Außer bei der Sortierung spielt das auch keinerlei Rolle. Solange die in allen Programmen gleich ist, spielt auch die Sortierung keine Rolle. An die Dudensortierung hält sich auch keiner, weil dem Normalbürger nicht beizubringen ist, das Torsten von Mueller anders einzusortieren ist als Torsten Von Mueller. Auch in sämtlichen Schnittstellen wird der Namenszusatz nicht übergeben und ausgewertet, außer in den Basisdaten.

Eure Entscheidung hätte auch Auswirkungen auf alle anderen Reports (Namenslisten, Stammblätter, Schulbescheinigungen etc.). Man sollte das Feld und das Feld weitere Vornamen abschaffen.

**Comment by M-Plu** [comment]
Sollte mit der Zeugnisversion vom Oktober 2021 behoben sein.
