### ISSUE TITLE
Graustufe der Notenfelder

### ISSUE THREAD

**Issue by Raffenberg** [SVWS-NRW/Schild-NRW-Zeugnisse-Sek1#47]
Hallo Zusammen,
einige meiner Schulen berichten, dass der Hintergrund der Zeugnisnotenfelder auf dem Monitor gut aussieht, aber im Ausdruck zu dunkel ist, so dass man die Note schlecht lesen kann. Das wird wohl an den Druckern liegen.

Ich habe überlegt, ob es nicht sinnvoll sein könnte, die Tönungsstufe in der .ini-Datei aufzunehmen. Hier könnte man entweder drei voreingestellte Stufen oder einen RGB-Wert akzeptieren. Im Zeugnisreport müsste man eine globale Integervariable definieren, welcher man bei der Auswertung der Ini-Datei über die RGB-Funktion den Farbwert zuordnet und diesen dann in den einzelnen Subreports abruft.

**Comment by mueller-falko** [comment]
Hallo Jens,
das ist in den Sek I Zeugnissen schon umgesetzt. Es gibt in der INI den Parameter "FarbeNotenfeld" , der mit "192,192,192" als RGB vordefiniert ist.

**Comment by Raffenberg** [comment]
Hallo Falko,
Stimmt, das hatte ich noch gar nicht registriert, obwohl es ja schon länger drin ist. Vielen Dank für den Hinweis. Die Anfrage kam von einer Grundschule, weshalb ich nur in der ini-Datei der Grundschulen nachgeschaut hatte.
