### ISSUE TITLE
Rechtsbehelfsbelerung im franz./bili Abiturzeugnis

### ISSUE THREAD

**Issue by mueller-falko** [SVWS-NRW/Schild-NRW-Zeugnisse-Sek1#48]
Ich habe gerade in der Anlage 12 die Rechtsbehelfsbelehrung angepasst. Das müsste ja jetzt wahrscheinlich auch noch in der französischen Variante passieren, aber dazu fehlen mir die Sprachkenntnisse.

**Comment by M-Plu** [comment]
Welche Anlage der APO-GOSt meinst du denn? Ich finde da nur eine Bescheinigung (Anlage 14) aber kein Zeugnis. Und die Bescheinigung hat kein Rechtsbehelfsbelehrung.

Sollte das Formular nicht in der APO-GOSt als Zeugnis aufgeführt sein, würde ich es aus der Formularsammlung entfernen. 

Aus meiner Sicht handelt es sich bei nicht um ein offizielles Dokument, sondern eine Übersetzung und ob das bei einem Zeugnis so statthaft ist, weiß ich nicht.

**Comment by mueller-falko** [comment]
Im GitHub sind im Ordner GymOb/Calibri/Abitur zwei Reports GymOb_Anl12_JgQ2_B_Abiturzeugnis_bil-frz
Die meine ich.

**Comment by M-Plu** [comment]
Das sind keine mir offiziellen Formular. Warum die in der Sammlung sind, weiß ich nicht. Evtl. kann Frank da etwas zu sagen.

**Comment by FPfotenhauer** [comment]
Hat Herr de la Haye mal gemacht.
Wir können die auch raus nehmen, wenn die nicht in der BASS sind.

**Comment by M-Plu** [comment]
Als Anlage der APO-GOSt finde ich die Dokumente nicht. Daher würde ich sie aus der Sammlung nehmen. Es handelt sich dabei ja um kein offizielles Dokument.

**Comment by M-Plu** [comment]
Frank nimmst du das aus den Zeugnissen raus oder machen wir das?

**Comment by FPfotenhauer** [comment]
Kannst du bitte gerne rausnehmen.
Sollen wir das einzeln noch zur Verfügung stellen?

**Comment by M-Plu** [comment]
Wenn du auf der Zeugnisseite dafür einen Bereich hast, könnte man es dort ablegen. Wenn du es gesichert hast, gib mir kurz Bescheid, dann nehme ich es raus.

**Comment by FPfotenhauer** [comment]
Ist gesichert!

**Comment by M-Plu** [comment]
Ist raus.
