### ISSUE TITLE
Folgeklasse 10.1

### ISSUE THREAD

**Issue by FPfotenhauer** [SVWS-NRW/Schild-NRW-Zeugnisse-Sek1#49]
In den neuen Formularen steht bei Folgeklasse 101, wenn dort 10.1 eingestellt ist.

Wurde dort etwas verändert? Die alten Formulare klappen.

**Comment by mueller-falko** [comment]
wir haben an der Stelle in der Tat was geändert. Früher wurde die Klassenbezeichnung zerlegt: die ersten beiden Zeichen wurden der Jahrgang, der Rest die Parallelität. Da hatten wir aber Probleme bei den Schulen, die keine führende Null in der Klassenbezeichnung hatten, was dann zu Fehlermeldungen führte, wenn das Folgejahr berechnet werden sollte (z.B. bei Vorversetzung). Daher wird in der neuen Berechnung als Jahrgang der ASD-Jahrgang benutzt und als Parallelität das letzte Zeichen der Klasse. Wir haben uns da an der ASD-Bezeichnung orientiert. Eine Programmierung, die bei allen Klassenbezeichnungen funktioniert, ist schwierig.
Man könnte natürlich auch konsequent die eingetragene Folgeklasse ausgeben. Das funktioniert aber nur dann fehlerfrei, wenn die Nutzer bei Nicht- bzw. Vorversetzung die Folgeklasse anpassen.

**Comment by M-Plu** [comment]
Ich sehe das so wie Falko, allgemein für alle Fälle so etwas zu definieren, ist schwierig. Das über die Folgeklasse zu machen, sehe ich als schwierig an, weil SchILD das ja nicht automatisch macht.
Mir fallen da nur zwei Lösungen ein. 
- Eine weitere INI-Einstellung ergänzen, die die Länge der Parallelität definiert.
- Die Parallelität weglassen, sprich: "Er/Sie geht in die Klasse 10 über" statt "geht in die Klasse 10A/10.1 über"

**Comment by FPfotenhauer** [comment]
Insgesamt gibt es an Gesamtschulen schon öfter diese 10.1 Bezeichnungen.

![SNAG_2021_06_22_14 58 54](https://user-images.githubusercontent.com/34127980/122928708-6afea700-d36a-11eb-8998-65598193b200.png)

Das aus der BASS würde wohl für die zweite Lösung sprechen...

**Comment by FPfotenhauer** [comment]
Ich bin nach den neuesten Meldungen im Forum nun sogar dafür einfach die Folgeklasse abzudrucken.
Ggf. könnte man prüfuen, ob die erste Ziffer eine Null ist und nur dann diese wegnehmen...

**Comment by mueller-falko** [comment]
Da haben wir aber das Problem, dass die Kollegen immer die Folgeklasse anpassen müssen, wenn jemand nicht versetzt wird, da das ja nicht automatisch passiert. Ich könnte mir auch folgendes vorstellen:
Man prüft, ob das erste Zeichen der Folgeklasse eine 0 oder eine 1 ist. Wenn ja, löscht man die ersten beiden Zeichen und nimmt den Rest als Parallelität, wenn nicht, löscht man nur das erste Zeichen. Den Rest der Programmierung könnte man dann so lassen.
Oder man nimmt bei versetzten die Folgeklasse und bei allen anderen druckt man nur die Jahrgangsstufe.

**Comment by mueller-falko** [comment]
Wie auch immer, ich könnte versuchen, das am Wochenende umzusetzen, so dass man für nächste Woche noch ein Update hochladen könnte.

**Comment by FPfotenhauer** [comment]
Ich würde nur bei versetzen die Folgeklasse drucken.
Bei den anderen die JGStufe.
Mir wäre es nicht so super wichtig, dass das noch nächste Woche kommt. 
Den Schulen würdest du aber sicherlich einen großen Gefallen tun....

**Comment by mueller-falko** [comment]
Ich habe das jetzt in allen Halbjahreszeugnisse und im Überweisungszeugnis GY angepasst, allerdings quick and dirty:
Zu Beginn wird die folgeklasse auf '' gesetzt, dadurch verschwindet sie bei allen Versetzungsvermerken.
Bei "V" wird folgestufe auf die Folgeklasse aus Schild gesetzt. Eine führende 0 hab ich gelöscht.
Das gleiche passiert übrigens bei "freiwillig zurück", weil wir ja davon ausgehen, dass der Schüler grundsätzlich versetzt ist. Das wird gerade aber auch im Forum wieder diskutiert.
Bitte testen und dann veröffentlichen.

**Comment by M-Plu** [comment]
Sollte mit der Zeugnisversion vom Oktober 2021 behoben sein.
