### ISSUE TITLE
Klassenlehrer/in krank, Stellvertreter/in unterschreibt

### ISSUE THREAD

**Issue by Raffenberg** [SVWS-NRW/Schild-NRW-Zeugnisse-Sek1#50]
Hallo zusammen,
ich vermisse immer mal wieder die Möglichkeit, dass die stv. Klassenleitung die Zeugnisse unterschrieben, wenn die Klassenleitung verhindert oder krank ist. Momentan unterschrieben die Stellvertreter mit i.V. über der Unterschriftenlinie mit falscher Untertitelung.
Immer wenn das vorkommt, vermisse ich die Möglichkeit, in der ini einen Schalter zu setzen, welcher einfach eine Textabfrage zum unterschreibenden Lehrer macht. Den könnte man dann bei diesem Zeugnissatz bedienen und dann wieder zurückstellen.

Ich stelle das einfach mal zur Diskussion, da das Thema ja nicht ganz so einfach ist.

**Comment by mueller-falko** [comment]
Ich finde die Idee gut. Ich verwende bei uns an der Schule für die Oberstufenzeugnisse eine Abfrage, in der man nur das Lehrerkürzel eingeben muss. Den Rest holt der Report dann aus der DB. Da wir pro Stude drei Beratungslehrer haben, von denen in der Regel nur einer unterschriebt, ist das für uns die praktischste Lösung. Man könnte ja mal drüber Nachdenken, so eine Option in die INI mit einzubauen.

**Comment by mueller-falko** [comment]
Das stimmt.

**Comment by Raffenberg** [comment]
Die Variante mit dem Kürzel gab es früher einmal in den ganz alten Zeugnissen. Dort erschien vor dem Druck ein Text-Eingabefenster, wo vorausgefüllt das Kürzel des Klassenlehrers eingetragen war, welche man dann entweder bestätigen konnte, oder durch das Kürzel des Lehrers ersetzt, welcher unterschreiben sollte. Das war sehr praktikabel.
Wenn man etwas ähnliches in der ini aktivieren könnte, fände ich das gut.

Beste Grüße an alle.

**Comment by M-Plu** [comment]
Ist in die Zeugnisse der Sek-I bereits integriert und auch in den Sek-II-Zeugnissen, die mit INI-Unterstützung erscheinen werden. Ich schließe daher hier das Issue. Bei Fehlern einfach ein neues aufmachen.
