### ISSUE TITLE
Anlage 56 versetzt

### ISSUE THREAD

**Issue by FPfotenhauer** [SVWS-NRW/Schild-NRW-Zeugnisse-Sek1#51]
![SNAG_2021_06_29_12 29 45](https://user-images.githubusercontent.com/34127980/123782741-efef4080-d8d5-11eb-9e1a-c621355393f9.png)

In SK anlage 56 Zeugnis 6-10 steht das in der BASS, warum auch immer.
Unser Zeugnis aht abe rdie Programmierung der GE bis zur 9 steht da "Geht über" ab der 9 kommt "Versetzt".
Das ist bei den Kooperativen aber m.E. falsch, das ist ja nach RS oder HS und da wird ab er Klasse 6 "versetzt".

**Comment by M-Plu** [comment]
Sollte mit der Zeugnisversion vom Oktober 2021 behoben sein, da dort der beginn der Versetzung in der INI-Datei gesetzt werden kann.
