### ISSUE TITLE
Informatik in Sek1

### ISSUE THREAD

**Issue by FPfotenhauer** [SVWS-NRW/Schild-NRW-Zeugnisse-Sek1#53]
Die Änderungen bei Wirtschaft/Politik und Informatik betreffen auch das Fach Informatik.
Im Snapshot wurde eine neue Fächergruppe "Informatik Sek1" eingefügt.

Informatik soll nicht mehr als Naturwissenschaft gelten.
Und soll auch nicht "eingerückt" in dieser Fächergruppe erscheinen.

Ich habe im Fachreferat gesagt, dass wir das zum Halbjahr wahrscheinlich nicht können, aber zum Schuljahr müsste das bitte umgesetzt werden.

**Comment by mueller-falko** [comment]
Wenn ich in der Datenquelle "Naturwissenschaften" das Fach Informatik rausfiltern möchte, habe ich das Problem, dass es in der Datenquelle "Naturwissenschaften" kein Datenfeld mit der ASD-Bezeichnung des Fachs gibt. Ich kann also nur auf die internen Fachkrz. zugreifen. Wenn also eine Schule für Informatik eine andere interne Kurzform als "IF" benutzt, wird die Filterung nicht funktionieren. Setzen wir das Fachkrz. "IF" voraus, oder soll ich irgendwie anders an die Sache herangehen.
