### ISSUE TITLE
Versetzungsvermerk RS mit HS-Bildungsgang

### ISSUE THREAD

**Issue by mueller-falko** [SVWS-NRW/Schild-NRW-Zeugnisse-Sek1#54]
Die Funktion Versetzungsvermerk muss noch so angepasst werden, dass der Hinweis mit 10A/10B auch bei RS mit HS-Bildungsgang erscheint.

**Comment by M-Plu** [comment]
Falko hat das entsprechend in die aktuelle Version eingepflegt. Ich schließe daher das Issue. Bei Fehlern bitte ein neues Issue erstellen.
