### ISSUE TITLE
Embeddet Fonts in Zeugnis PDF

### ISSUE THREAD

**Issue by Raffenberg** [SVWS-NRW/Schild-NRW-Zeugnisse-Sek1#58]
Hallo Zusammen,
Mir sind in der ini zwei Schalter zu den PDFs aufgefallen.
1.	Schriftarten in PDF einbetten.
2.	Schriftarten als ANSI/Unicode einbetten

Meiner Meinung nach darf man beide nicht anbieten! Andernfalls läuft man zum einen Gefahr, dass Sonderzeichen in Schülernamen nicht ordnungsgemäß gedruckt werden, was bei einem Zeugnis keine gute Idee wäre. Zweitens sieht ein Zeugnis ohne eingebettet Fonts teils fürchterlich aus. Ich habe schon einige gesehen. 

Ich hatte das Problem mit großen PDF-Dateien in meinen Serienbriefen zunächst auch.Ich habe in meinen Serienbriefen durchweg Unicode und Schriftarten eingebettet, allerdings die Option „efUseSubset“ und nicht „efAllFonts“ genutzt. Das macht die PDF-Dateien bedeutend kleiner und ist eine gute Generallösung, ohne ini-Schalter.

**Comment by M-Plu** [comment]
Normalerweise sollte die PDF-Datei ohne eingebettete Schriftarten genauso aussehen wie mit Einbettung, wenn die verwendeten Schriften auf dem System installiert sind. Daher werden diese Optionen auch als Optionen geführt. 

Was die Einstellung efUseSubset betrifft. Was bedeutet das genau? Wenn es keine negativen Auswirkungen hat, können wir das gerne überall aktivieren.

**Comment by Raffenberg** [comment]
Mir sind diese Probleme mit Zeugnissen in falscher Darstellung schon mehrfach selbst, aber auch bei anderen Schulen begegnet. Anscheinend hängt das nicht nur davon ab, ob der Font auf dem System installiert ist, sondern auch davon, welchen PDF-Reader man betrachtet. Ich kann auch nicht genau sagen, woran das liegt.

efUseSubset bedeutet, dass nicht der ganze Schriftsatz eingebettet wird, sondern nur diejenigen Zeichen, die in dem Zeugnis verwendet werden. Dadurch beschränkt sich die Einbettung im kern auf die Buchstaben des Alphabets, wodurch die PDF-Dateien kaum merklich größer werden. Ist meiner Meinung nach der perfekte Kompromiss und könnte damit auch die Standardoption sein, wenn es bei einer Option bleiben sollte.

Ich denke halt an die User. Denen müsste man zum einen erklären, wo der Unterschied zwischen ANSI und Unicode und dem Einbetten von Schriftarten liegt. Ich schätze, dass man dem User argumentativ kaum erklären kann, dass die Standardeinstellung dazu führt, dass keine Sonderzeichen im PDF zu sehen sind und dass das Zeugnis in Abhängigkeit vom PDF-Reader komisch aussieht. Wer so ein Zeugnis schon mal gesehen hat, weiß, was ich meine. Das System greift dann auf so eine Schreibmaschinenschrift aus den 80ern zurück.

**Comment by M-Plu** [comment]
OK, dann würde ich bei den kommenden Sek-II Zeugnissen die entsprechenden PDF-Einstellungen setzen und die beiden Optionen auf Ja bzw. Unicode setzen, wenn es so ist, wie du beschreibst. Wichtig ist halt nur, dass die PDF-Dateien nicht zu groß werden.

Das hört sich für ein wenig so an, als ob die PDF-Implementation der Reporting nicht die sauberste ist. Aber daran können wir ja nichts ändern.

Für die Sek-I könnte Falko das evtl. ebenfalls anwenden?

**Comment by M-Plu** [comment]
So ich die Optionen nun gesetzt (Unicode + efUseSubset). 

Dazu aber ein wichtiger Hinweis: die Option in der INI bzgl. des Einbinden der Fonts funktioniert nicht und funktionierte nie (auch nicht in der Sek-I) weil ich damals (Februar 2020) die Zeile erstmal auskommentiert hatte, weil ich leider die richtige Syntax dafür nicht finden konnte. Diesbezüglich habe ich nun eine Anfrage bei Digital Metaphors gestellt. Mal sehen wann die antworten.

Ich schreibe euch eine E-Mail, wenn die "finalen" Zeugnisse zum Testen fertig sind. Ich muss noch einen Bug im Infoblock fixen und das Abiturzeugnis layouten, damit es sich in die Formatierungen der anderen Zeugnisse einfügt.
