### ISSUE TITLE
Texteingabe bei Zeugnisunterschriften

### ISSUE THREAD

**Issue by Raffenberg** [SVWS-NRW/Schild-NRW-Zeugnisse-Sek1#59]
Hallo zusammen,
bei der Option zur Texteingabe würde ich den Einleitungstext ergänzen z.B. zu 
"Bezeichnung Unterschriftenfeld Schulleitung (Erklärung siehe ini-Datei). Die Eingabe eines Lehrkraftkürzels ist möglich.

Mir ist aufgefallen, dass die Texteingabe nur beim Aufruf des Zeugnisses abgefragt wird. Damit ist nur eine Klassenweise Ausgabe möglich. Besser wäre, wenn nach einem Klassenwechsel erneut die Texteingabe erfragt würde.

**Comment by M-Plu** [comment]
Ich weiß nicht, ob der beschreibende Text mehrzeilig sein kann, muss ich später mal testen, sonst wäre das OK.

Die Eingabe sollte ja nur eine Notlösung sein. Und meiner Meinung nach kann man dann auch eine vorherige Filterung akzeptieren. Oder hast du fälle, wo dies regulär/regelmäßig genutzt wird?

**Comment by Raffenberg** [comment]
Nein. Ich gebe dir recht. In meinem Alltag würde ich das auch nur Klassenweise benutzen. Ich kann natürlich nicht genau sagen, ob andere hier anders arbeiten.

Es gab früher mal bei den Zeugnissen eine Lösung, die ich dauerhaft genutzt hatte. Da wurde bei der Option "Texteingabe" im Textfenster bereits diejenige Anzeige angezeigt, die automatisch eingefügt worden wäre (bei mir also J. Raffenberg, StD). Die konnte man dann im Regelfall mit Enter verabschieden. In den Sonderfällen konnte man dann entweder einen Text, oder ein Kürzel eingeben. Das war sehr praktisch. Nach Eingabe eines Kürzels wurde damals sogar das Fenster nochmals angezeigt, nun mit dem neuen Text, der zu dem Kürzel gehörte. Das war sehr transparent, da man immer genau wusste, was unter den Unterschriftenfeldern stehen würde, so dass ich das dauerhaft verwendet und gemocht hatte.

**Comment by M-Plu** [comment]
OK, eine solche Variante habe ich nie kennengelernt und irgendwie steht sie der Idee der INI-Dateien entgegen. Daher würde ich aus meiner Sicht da keine weitere Implementation vornehmen, aber vielleicht sehen die anderen es ja noch anders.

**Comment by Raffenberg** [comment]
Ich finde nicht, dass das der Idee der ini-Datei entgegen steht, sondern den Schalter "T" für den User transparenter in seiner Auswirkung macht. Das wäre natürlich ein Punkt, der hier etwas breiter diskutiert werden sollte.
