### ISSUE TITLE
Informatik Sek 1

### ISSUE THREAD

**Issue by FPfotenhauer** [SVWS-NRW/Schild-NRW-Zeugnisse-Sek1#60]
Ich wusste, dass es einen Grund hat, warum wir das mit der eigenen Datenquelle gemacht haben.
Verstehe ich es richtig, dass das ASD-Kürzel nicht in der Zeugnisdatenquelle enthalten ist?

**Comment by FPfotenhauer** [comment]
Mir stellt sich da die Frage, wie viel Aufwand das wäre.
Das ASD-Kürzel zu haben, wäre ja auch für Schild3 interessant...

**Comment by JuergenRichter** [comment]
Rückfrage: Wozu wird denn das ASD-Kürzel benötigt?

**Comment by JuergenRichter** [comment]
Grundsätzlich ist es natürlich kein Problem, das in der Datenquelle (bzw. dann in allen Zeugnis-Datenquellen, sind alle gleich aufgebaut) unterzubringen.

**Comment by Raffenberg** [comment]
Informatik soll auf den Zeugnissen der SI (im Gegensatz zu den Zeugnissen der SII) nicht im Block der Naturwissenschaften gelistet werden, sonder eine eigene, nicht eingerückte Zeile erhalten. Die einfachste Möglichkeit dies zu realisieren wäre, bei den bestehenden Zeugnissen Informatik in den Naturwissenschaften auf "invisible" zu setzen. Zusätzlich wird in einem weiteren identischen Subreport genau das Gegenteil gemacht, so dass dort nur noch Informatik "visible" ist. Hierzu ist jedoch zwingen die Ausschau nach dem eindeutigen ASD-Kürzel notwendig.
Man erspart sich mit diesem Trick unverständliche Änderungen an der Fächertabelle durch den Nutzer und durch uns.

**Comment by JuergenRichter** [comment]
OK, baue ich ein.

**Comment by JuergenRichter** [comment]
Frage: Wird denn dann die neue Datenquelle "Informatik" überhaupt benötigt?

**Comment by Raffenberg** [comment]
Nein. Die ist Überflüssig und kann mit einem der kommenden Updates wieder rückabgewickelt werden.

**Comment by FPfotenhauer** [comment]
Ich würde die dann aus der Schildintern rausnehmen.
In der Reportiing könnte die erst einmal "auskomentiert" werden.

**Comment by JuergenRichter** [comment]
Ist umgesetzt
