### ISSUE TITLE
Textformat der INI-Datei

### ISSUE THREAD

**Issue by mueller-falko** [SVWS-NRW/Schild-NRW-Zeugnisse-Sek1#61]
Beim Testen neuer Optionen ist mir heute aufgefallen, dass Umlaute aus der INI nicht korrekt eingelesen werden. Wenn ich z.B. UnterschriftenKLText=Müller benutze, kommt das ü nur kodiert an. Es funktioniert aber, wenn ich die INI-Datei im Format ANSI abspeichere. Spricht etwas dagegen, das grundsätzlich als Format zu benutzen?

**Comment by M-Plu** [comment]
Welchen Editor benutzt du denn? Die Datei ist in ANSI gespeichert, das die Reporting nur ANSI einlesen kann. Bei mir wird das im Windows Editor auch richtig angezeigt.

**Comment by mueller-falko** [comment]
Ich nutze auch den Windows Editor. Ich habe gerade nochmal nachgesehen, bei einigen Schulformen (RS, SK) sind die INIs in ANSI, bei anderen (GY, GE, HS) sind sie in UTF-8. Keine Ahnung, warum. Werde sie jetzt alle in ANSI abspeichern.
