### ISSUE TITLE
Fußnoten bzgl. Informatik

### ISSUE THREAD

**Issue by mueller-falko** [SVWS-NRW/Schild-NRW-Zeugnisse-Sek1#62]
https://schulverwaltungsinfos.nrw.de/svws/forum/viewtopic.php?f=16&t=4431
Ich sehe es auch so, dass die Fußnote entfallen kann, da Informatik ja nur auf dem Zeugnis erscheint, wenn es tatsächlich unterrichtet wird. Ist das so korrekt?

**Comment by FPfotenhauer** [comment]
Haben wir bisher ja immer so umgesetzt.
Die Diskussion hatte ich mit Jochen bei den BK-Zeugnissen auch.
Auch dort haben wir gesagt, dass solche Fußnoten entfallen können.
Hier ist das etwas kritische, weil die Fußnote irgendwie auch eine Information enthält, aber eigentlich rührt die nur daher, dass bei "leeren Notenfeld" eine Erklärung her muss, warum das leer ist, das ist bei uns ja nicht der Fall!
