### ISSUE TITLE
Lernbereichsnoten im HS-Bildungsgang der RS

### ISSUE THREAD

**Issue by mueller-falko** [SVWS-NRW/Schild-NRW-Zeugnisse-Sek1#66]
https://schulverwaltungsinfos.nrw.de/svws/forum/viewtopic.php?f=16&t=4572&p=27156#p27156

Weiß da einer von euch Bescheid, wie das da laufen muss?

**Comment by FPfotenhauer** [comment]
Beim HA9 gibt es keine Lernbereichsnoten!

**Comment by mueller-falko** [comment]
Demnach ist Anlage 30 fehlerhaft in der Bass dargestellt?

**Comment by FPfotenhauer** [comment]
Nein. im HS-Bildungsgang wir NW und AL Lernbereichsnote.
In der RS ist das NW und GL.

Bitte nicht festnageln, ich brauche erstmal einen Kaffee...

**Comment by mueller-falko** [comment]
Aber das ist doch genau das Problem: du sagstim HS-Bildungsgang gibt es in AL eine Lernbereichsnote. Aber Anlage 30 sieht nur eine Note im Wahlpflichtfach AL vor und es werden auch nicht die einzelnen Fächer in Klammern aufgeführt, so wie es bei NW der Fall ist. Dadurch ist der Forumsbeitrag ja überhaupt erst entstanden.

**Comment by FPfotenhauer** [comment]
Ich kann es mir nicht genau ansehen, aber vergleiche es doch mal mit dem HS-Zeugnis aus der BASS.

**Comment by FPfotenhauer** [comment]
Ich vermute, dass "Wahlpflichtfach Wirtschaft und Arbeitswelt" die LBN ist.

**Comment by mueller-falko** [comment]
Genau da gibt es den Unterschied. Anlage 17 (HA10 der HS) gibt den Lernbereich AL an, Anlage 30 (HA10 des HS-Bildungsgangs an der RS) nicht.

**Comment by mueller-falko** [comment]
> Ich vermute, dass "Wahlpflichtfach Wirtschaft und Arbeitswelt" die LBN ist.

Aber das muss ja ganz anders in Schild gepflegt werden. Im Lernbereich gibt es einzelne Fächer und ich trage im Akt. Abschnitt die Lernbereichsnote ein, beim Wahlpflichtfach muss ich ein eigenes Fach AL einrichten und die anderen werden nicht berücksichtigt. Es ist halt irgendwie nicht einheitlich und daher verwirrend.

**Comment by FPfotenhauer** [comment]
Ich habe gerade eine Mail an Frau Witt geschrieben.

**Comment by mueller-falko** [comment]
Ok, danke. Ich habe gerade auch nochmal in Anlage 29 (HA des HS-Bildungsgangs an der RS) nachgesehen: da gibt es auch keine Einzelfächer für den Bereich AL sondern nur das WP-Fach. Wenn man also von den Anlagen aus geht, scheint es im HS-Bildungsgang an der RS keine einzelnen Fächer im Bereich AL zu geben im Unterschied zur Hauptschule. Nur dazu finde ich nichts in der BASS.
