### ISSUE TITLE
Feldgrößen anpassen

### ISSUE THREAD

**Issue by mueller-falko** [SVWS-NRW/Schild-NRW-Zeugnisse-Sek1#67]
1.       In Zeugnisreport „Anlage 46 …“ ist im „SubReport_AUE: …“ und „SubReport_ASV: …“ die Länge des Feldes „Memo_ASV“ nicht korrekt eingestellt (Breite voll, nicht auf ~641 wie im Report „Anlage 48 und 49“). Die Zeugnisbemerkungen werden daher außerhalb des Papierbereichs gedruckt.
 
2.       Die Feldgrößen für den Ergänzungsunterricht, die Arbeitsgemeinschaften und sonstigen Fächer des „Weiteren Unterrichts“ sind zu klein. Der Textzug „Mit besonderem Erfolg teilgenommen“ wird infolgedessen abgeschnitten.

**Comment by mueller-falko** [comment]
Den ersten Punkt habe ich jetzt korrigiert. 
Den zweiten kann ich nicht bestätigen. Bei mir passt das perfekt in das graue Feld. Ich weiß leider auch nicht mehr, woher diese Meldung kam.

**Comment by AnneSchueller** [comment]
Ich habe das auch gerade mal getestet. "Mit besonderem Erfolg teilgenommen" passt sowohl im Zeugnis als auch im Überweisungszeugnis von Re/Gy/Ge/Hs perfekt rein.
