### ISSUE TITLE
Umgang mit non-binären Kindern

### ISSUE THREAD

**Issue by mueller-falko** [SVWS-NRW/Schild-NRW-Zeugnisse-Sek1#70]
Er/sie durch Vorname ersetzen usw.

**Comment by FPfotenhauer** [comment]
Ich schreibe das jetz tmal hier, damit das dann auch dokumentiert ist.

Leider war ich davon ausgegangen, dass hier ER/Sie nur im Fall divers und ohne Angabe durch den Vornamen ersetzt wird.
Da kann man jetz aber drüber reden, ob das jetzt einfach so bleibt.

Im Falle der Zuweisungen muss das auber bei Divers und ohne Angabe auf jeden Fall geändert werden, denn dort ist ER/Sie ja definitiv falsch.

Die globalen neutralen Änderungen kommen wahrscheinlich erst später.
Kannst du das dann bitte noch ändern?
Wenn Fragen sind, bitte melden.

**Comment by mueller-falko** [comment]
Das muss aber in den beiden letzten Abfragen auf "= 5"  und "=6" geändert werden. 4 ist weiblich.

**Comment by FPfotenhauer** [comment]
Ja. War ein Copy Paste Fehler und nur ein Beispiel.
