### ISSUE TITLE
Inklusionszeugnisse; Halbjahresbezeichnung von Gesamtschulen

### ISSUE THREAD

**Issue by AnneSchueller** [SVWS-NRW/Schild-NRW-Zeugnisse-Sek1#72]
Nur bei Inklusionszeugnissen und Lernstandsberichten:
Bei Gesamtschulen ist die Bezeichnung zum Halbjahr falsch:
2. Quartal --> 2. Halbjahr
4. Quartal --> 4. Halbjahr

**Comment by mueller-falko** [comment]
Mit den Inklusionszeugnissen habe ich mich bisher nie befasst, sie sind deutlich anders aufgebaut als die von Herrn DeLaHeye. Ich denke aber, dass ich das mit den Halbjahren hinbekomme. 
Ich habe allerdings eine Frage zu den Reports, die Anne im Forum gepostet hat: 
Der Report "Sek1-Inklusionszeugnis_Hybridform.rtm" hat im Kopf einen Verweis auf den 
Dynamischen SubReport "Sek1-Lernstandsbericht_Kopf.rtm". Trotzdem wird bei mir der von Anne geänderte Kopf 
"Sek1-Inklusionszeugnis_Kopf.rtm" geladen. Wie kommt das?

**Comment by FPfotenhauer** [comment]
Die Zeugnisse sind eigentlich von den GS Zeugnissen abgeleitet.
Bei Fragen können wir auch gerne Herrn Richter ansprechen. Ich kann aber auch schauen.

**Comment by mueller-falko** [comment]
Ich hab das jetzt im Inklusionszeugnis und im Lernstandsbericht so angepasst, das bei Quartalen 1+2 "1. Halbjahr" ausgegeben wird und bei Quartalen 3+4 "2. Halbjahr". Die Kopfdateien musste ich dafür nicht ändern.
Werden diese Änderungen auch in den Ankreuzzeugnissen benötigt, oder sind die nur für GS gedacht? Bei diesen Zeugnissen wird nämlich in der Programmierung u.a. mit den Jahrgängen E1, E2 und E3 gearbeitet.

**Comment by AnneSchueller** [comment]
Hallo Falko,
auch an dieser Stelle nochmal: Herzlichen Dank, dass du das angepasst hast.
Nach Rücksprache mit Herrn Richter sind die  Ankreuzzeugnisse, die im Paket Inklusion_Lernstand sind, ebenfalls für weiterführende Schulen.  In wieweit die wirklich zum Einsatz kommen, weiß ich nicht.

**Comment by mueller-falko** [comment]
Vielleicht sollten wir langfristig überlegen, die Inklusionszeugnisse an "unsere" INI anzupassen. Die Vorlagen scheinen ja immer öfter benötigt zu werden. Gibt es für die Inklusionszeugnisse eigentlich irgendwelche formalen Vorgaben?

**Comment by AnneSchueller** [comment]
Den Gedanken hatte ich auch schon. Die GS-Zeugnisse sind relativ ähnlich aufgebaut. Die würde ich auch gerne anpassen. Ich schaue nach der Zeugniswoche mal nach formalen Vorgaben.

**Comment by AnneSchueller** [comment]
Vorlage:
https://www.schulministerium.nrw/sites/default/files/documents/Muster-Lernstandsbericht.pdf

**Comment by AnneSchueller** [comment]
Für eine Anpassung laut Vorlage müssten auch in Schild selbst Anpassungen erfolgen (beispielsweise um die Angabe zum Umfang abzufragen)
Da das in SchILD2 definitiv nicht mehr kommen wird, schließe ich das Issue
