### ISSUE TITLE
Unterschrift durch Abteilungsleitungen

### ISSUE THREAD

**Issue by Raffenberg** [SVWS-NRW/Schild-NRW-Zeugnisse-Sek1#75]
https://schulverwaltungsinfos.nrw.de/svws/forum/viewtopic.php?p=30730#p30730

An Gymnasien passt der Begriff "Abteilungsleiter" nicht so gut. Ich habe Herrn Richter gebeten, einen Zugriff auf das Datenfeld "Bezeichnung" in den Klassengruppen/Abteilungen zu ermöglichen. Dies ist in dem Update vom 19.1.2023 umgesetzt. Somit kann man nun dort Bezeichnungen wie Mittelstufenkoordination / Mittelstufenkoordinator / Mittelstufenkoordinatorin etc. hinterlegen und könnte in den Zeugnisreports darauf zuzugreifen. Damit könnte der User das Unterschriftenfeld stärker steuern und auch selbstständig das Geschlecht der Abteilungsleitung definieren.

Einen Pferdefuß gibt es, wenn an den Gesamtschulen der Begriff Abteilungsleitung üblich und damit mehrfach besetzt ist. In den Klassengruppen/Abteilungen darf jeder Begriff nur eindeutig vorkommen. An Gymnasien ist das konkret benannt. Wie das an Gesamtschulen oder anderen Schulformen aussieht, weiß ich nicht.

**Comment by Raffenberg** [comment]
An so etwas hatte ich auch gedacht. Das wäre zumindest nur ein neuer Buchstabe in der ini und kein neuer Schalter.
Bei B würde man den Text dann in keinster Weise anpassen und darauf vertrauen, dass das korrekte Wort hinterlegt ist (männlich, weiblich, neutral). Bei A muss man an Abteilungsleiter bei weiblichem Geschlecht ein -in anheften, so wie es momentan ja auch realisiert wird. 

Der SLALText sollte doch in diesem Zusammenhang keine Rolle spielen, oder?

Berücksichtigen wir bei Wörtern wie "Klassenlehrer" bereits diverse Lehrkräfte (Klassenleitung)?

**Comment by mueller-falko** [comment]
Die neue Option ist jetzt enthalten.
