### ISSUE TITLE
Überweisungszeugnis HS: Schulpflicht erfüllt

### ISSUE THREAD

**Issue by mueller-falko** [SVWS-NRW/Schild-NRW-Zeugnisse-Sek1#76]
Eine Frage an die Experten:
laut BASS steht auf allen Überweisungszeugnissen, ob die Schulpflicht erfüllt ist oder nicht. Nur nicht beim Überweisungszeugnis der HS (Anlage 14) bzw. des HS-Bildungsgangs an der RS (Anlage 27).
Ist das korrekt, oder wurde das übersehen?

**Comment by AnneSchueller** [comment]
Hallo Falko,
ich habe eben einen HA-Experten bezüglich der Ausweisung der Schulpflicht bei Anlage 14 gefragt:
An seiner Schule wird auch bei Anlage 14 mit ausgegeben, ob die Vollzeitschulpflicht erfüllt wurde oder nicht. Er hat auch zur Absicherung nochmal einen Schulleiter einer anderen Hauptschule gefragt. Dort ist es analog.

Ich bin allerdings etwas irritiert, dass das in der Vorlage der BASS nicht explizit ausgewiesen wird.

**Comment by mueller-falko** [comment]
Hallo Anne, 
in den Vorlagen von Herrn de la Heye wurde der Satz mit ausgegeben, und daher bisher bei unseren Versionen auch. Daher wundert es mich nicht, dass es bei den von dir angesprochenen Schulen erscheint. 
Die Frage ist ja, ob das ein Fehler in der Vorlage ist oder in der BASS. 
Bei der Version, die ich gestern in den DEV-Branch geladen habe, habe ich es rausgenommen, da es nicht in der Bass steht. 
Bin aber nach wie vor unsicher, ob das so sein soll.

**Comment by mueller-falko** [comment]
Hat Franks Nachfrage im Ministerium irgendein Ergebnis in dieser Sache geliefert?

**Comment by Raffenberg** [comment]
In der Regel können insbesondere beim Überweisungszeugnis so viele Bemerkungen auf das Zeugnis gesetzt werden, dass damit alle Bedarfe ebgedeckt werden können. Hier ist dann halt der User gefragt. Ich würde mich zunächst nur an das halten, was wir an Vorlagen haben. Ein wenig müssen die User ja auch mal mitdenken...

**Comment by mueller-falko** [comment]
Am 17.9.23 erledigt
