### ISSUE TITLE
Neue Abschlussbezeichnung

### ISSUE THREAD

**Issue by mueller-falko** [SVWS-NRW/Schild-NRW-Zeugnisse-Sek1#77]
Hab gerade im Forum gelesen, dass es bald die neuen Abschlussbezeichnungen geben wird. Wie lauten denn die Kürzel, denn das müssen wir ja in den Abschlusszeugnissen, in denen der Abschluss aus der DB genommen wird, anpassen.

**Comment by AnneSchueller** [comment]
Hallo Falko,

wir haben morgen nochmal eine Videokonferenz, bei der es sich u.a. um die Kürzel der Abschlüsse geht. Danach kann ich hier ein Screenshot zu den Änderungen hochladen und dir zusätzlich schonmal die schildintern zur Verfügung stellen.

**Comment by AnneSchueller** [comment]
Hallo Falko,

meinst du mit den Kürzeln, diese hier, die im Report aufgelistet werden?

![2023-05-20_192958](https://github.com/SVWS-NRW/Schild-NRW-Zeugnisse-Sek1/assets/79116896/72e72d9b-91e6-44c2-ab09-3b301ea4397e)


Diese wurden wie folgt umbenannt:

![2023-05-20_192526](https://github.com/SVWS-NRW/Schild-NRW-Zeugnisse-Sek1/assets/79116896/eade9b17-878b-45e6-8cbf-d6af71f9b7d0)


Also aus FOR -> MSA; aus HA10 -> EESA und aus HA -> ESA bzw. HSA -> ESA

**Comment by mueller-falko** [comment]
Genau das meinte ich. Danke. Ich werde das zeitnah einpflegen.
