### ISSUE TITLE
Anlage 18 - Auszeichnung der Klasse mit Typ B

### ISSUE THREAD

**Issue by Raffenberg** [SVWS-NRW/Schild-NRW-Zeugnisse-Sek1#78]
Hallo Falko,
wenn ich nichts in der neusten APO übersehen habe, fehlt in der Anlage 18 die Ausweisung des Typs: "War zuletzt Schüler der Klasse 10 Typ B"

https://schulverwaltungsinfos.nrw.de/svws/forum/viewtopic.php?f=16&t=5636

**Comment by mueller-falko** [comment]
Ups, das ist mir beim Anpassen der Köpfe auf geschlechtsneutrale Formulierungen offenbar im Copy-and-Paste-Rausch entgangen. Wird umgehend korrigiert.

**Comment by mueller-falko** [comment]
Ist im DEV korrigiert. Sobald die neuen Abschlussbezeichnungen getestet sind, wird es veröffentlicht.
