### ISSUE TITLE
GE_Prognosemitteilung

### ISSUE THREAD

**Issue by FPfotenhauer** [SVWS-NRW/Schild-NRW-Zeugnisse-Sek1#8]
https://schulverwaltungsinfos.nrw.de/svws/forum/viewtopic.php?p=8550#p8550

Im SK-PAket ist einfach die alte Prgnosemitteilung enthalten.
Es müsste geprüft werden, ob das was da im Forum gemeldet wurde tatsächllich ein Fehler ist.

**Comment by M-Plu** [comment]
Schaust du da noch mal bitte drauf, Falko?
