### ISSUE TITLE
Klassenangabe auf Prognosemitteilung

### ISSUE THREAD

**Issue by mueller-falko** [SVWS-NRW/Schild-NRW-Zeugnisse-Sek1#85]
Jens hat den Wunsch weitergeleitet, dass auf der Prognosemitteilung die Angabe der Klasse zugefügt wird. 
Spricht etwas dagegen?
Mein Vorschlag wäre, sowohl im Text oben als auch bei dem Rückgabeabschnitt die Klasse hinter dem Namen des Schülers eingefügt wird, also 
"...bei gleichbleibenden Leistungen wird Ihr Sohn Max Mustermann, Klasse 9b, am Ender der Klasse 10 voraussichtlich..."
und
"Ich habe Ihre Nachricht vom XXX über den voraussichtlichen Abschluss meines Sohnes Max Mustermann, Klasse 9b, erhalten."

**Comment by AnneSchueller** [comment]
In der Apo-S1 habe ich keine verbindlichen Angaben zur Prognosemitteilung gefunden.

Die Ergänzungen, wie du sie oben vorgeschlagen hast, finde ich treffende und würde sie auf jeden Fall befürworten.

**Comment by mueller-falko** [comment]
Am 17.9.23 erledigt.
